apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-cicd-deploy
  name: java-cicd-svc
spec:
  ports:
  - port: 888
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-cicd-deploy
  type: NodePort
status:
  loadBalancer: {}
